/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clusters;

import java.util.ArrayList;
import java.util.Random;
//import java.util.List;
import javax.swing.JOptionPane;
import java.util.concurrent.ThreadLocalRandom;


/**
 *
 * @author mcv26
 */
public class ClustersGUI extends javax.swing.JFrame {

    /**
     * Creates new form ClustersGUI
     */
    
    private static ArrayList<Points> NPoints;
    Random Rand = new Random();
    ResultK resultado;
    
    public ClustersGUI() {
        initComponents();
        disableButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelValorK = new javax.swing.JLabel();
        textValorK = new javax.swing.JTextField();
        labelValorN = new javax.swing.JLabel();
        textValorN = new javax.swing.JTextField();
        RunButton = new javax.swing.JButton();
        labelKRecomendado = new javax.swing.JLabel();
        textValorKRecomendado = new javax.swing.JTextField();
        ValidateButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Generar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clustering");
        setBackground(java.awt.Color.orange);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.orange);
        setResizable(false);

        labelValorK.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        labelValorK.setText("Valor k =");

        textValorK.setBackground(new java.awt.Color(0, 204, 204));
        textValorK.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        textValorK.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 153), 2, true));
        textValorK.setHighlighter(null);
        textValorK.setSelectionColor(new java.awt.Color(255, 204, 0));

        labelValorN.setBackground(new java.awt.Color(0, 255, 0));
        labelValorN.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        labelValorN.setText("Valor N =");

        textValorN.setBackground(new java.awt.Color(0, 204, 204));
        textValorN.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        textValorN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 153), 2, true));
        textValorN.setHighlighter(null);
        textValorN.setSelectionColor(new java.awt.Color(255, 204, 0));

        RunButton.setFont(new java.awt.Font("Trajan Pro", 3, 18)); // NOI18N
        RunButton.setText("Correr");
        RunButton.setAlignmentY(0.0F);
        RunButton.setBorderPainted(false);
        RunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunButtonActionPerformed(evt);
            }
        });

        labelKRecomendado.setBackground(new java.awt.Color(0, 255, 0));
        labelKRecomendado.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        labelKRecomendado.setText("Valor k Recomendado =");

        textValorKRecomendado.setEditable(false);
        textValorKRecomendado.setBackground(new java.awt.Color(0, 204, 204));
        textValorKRecomendado.setFont(new java.awt.Font("MS UI Gothic", 0, 12)); // NOI18N
        textValorKRecomendado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 153), 2, true));
        textValorKRecomendado.setHighlighter(null);
        textValorKRecomendado.setSelectionColor(new java.awt.Color(255, 204, 0));

        ValidateButton.setFont(new java.awt.Font("Trajan Pro", 3, 18)); // NOI18N
        ValidateButton.setText("Validar Puntos");
        ValidateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidateButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );

        Generar.setFont(new java.awt.Font("Trajan Pro", 3, 18)); // NOI18N
        Generar.setText("Generar Puntos N");
        Generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(labelValorK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textValorK, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelValorN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textValorN, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(labelKRecomendado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textValorKRecomendado, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Generar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(RunButton)
                        .addGap(39, 39, 39)
                        .addComponent(ValidateButton)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValorK, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textValorK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelValorN, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textValorN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKRecomendado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textValorKRecomendado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValidateButton)
                    .addComponent(RunButton, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(Generar))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunButtonActionPerformed
        try{
        int valK = Integer.parseInt(textValorK.getText());
        if (valK <= 5){
            K_means_Algorithm algoritmo= new K_means_Algorithm();
            ResultK result = algoritmo.calcular(NPoints, valK);
        }else{
            JOptionPane.showMessageDialog(null,"Error de Valor N\nEl número debe de ser "
                    + "menor o igual a 5","Error",JOptionPane.WARNING_MESSAGE);
            disableButtons();
        }}catch(Exception e){
                JOptionPane.showMessageDialog(null,"Error de Tipo o Casilla en blanco"
                        + " \nSolo valores enteros son permitidos","Error",JOptionPane.ERROR_MESSAGE);
                disableButtons();
                }
        
        
    }//GEN-LAST:event_RunButtonActionPerformed

    private void ValidateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidateButtonActionPerformed
        
    }//GEN-LAST:event_ValidateButtonActionPerformed

    private void GenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarActionPerformed
       try{
        int valN = Integer.parseInt(textValorN.getText());
        if (valN >= 5){
            generarNPoints(valN);
            enableButtons();
        }else{
            JOptionPane.showMessageDialog(null,"Error de Valor N\nEl número debe de ser "
                    + "mayor o igual a 5","Error",JOptionPane.WARNING_MESSAGE);
            disableButtons();
        }
        }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Error de Tipo o Casilla en blanco"
                        + " \nSolo valores enteros son permitidos","Error",JOptionPane.ERROR_MESSAGE);
                disableButtons();
                }
                
    }//GEN-LAST:event_GenerarActionPerformed

    private void generarNPoints(int valN){
        int minimum = -5;
        int maximum = 5;
        
        NPoints = new ArrayList<>();
        ArrayList<String[]> auxPoint = new ArrayList<>();
        for(int i = 0; i<valN; i++){
           String[] point = new String[2];
           //ArrayList<Float> point = new ArrayList<>();
           
           //point.add(-5+Rand.nextInt(5));
           //point.add(-5+Rand.nextInt(5));
           point[0]=(Integer.toString(
                   ThreadLocalRandom.current().nextInt(minimum, maximum + 1)));
           point[1]=(Integer.toString(
                   ThreadLocalRandom.current().nextInt(minimum, maximum + 1)));
           //point.add(Rand.nextInt());
           auxPoint.add(point);
        }
        for(int i= 0;i<valN;i++){
            Points p = new Points(auxPoint.get(i));
            NPoints.add(p);
        }
    }
       
    private void disableButtons(){
        RunButton.setEnabled(false);
        ValidateButton.setEnabled(false);
    }
    
    void enableButtons(){
        RunButton.setEnabled(true);
        ValidateButton.setEnabled(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClustersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClustersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClustersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClustersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClustersGUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Generar;
    private javax.swing.JButton RunButton;
    private javax.swing.JButton ValidateButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelKRecomendado;
    private javax.swing.JLabel labelValorK;
    private javax.swing.JLabel labelValorN;
    private javax.swing.JTextField textValorK;
    private javax.swing.JTextField textValorKRecomendado;
    private javax.swing.JTextField textValorN;
    // End of variables declaration//GEN-END:variables
}
